all:
	gcc -o test_rtmon -O2 test_rtmon.c
	gcc -o test_print_rtmon -O2 test_print_rtmon.c
	gcc -o test_cancel_rtmon -O2 test_cancel_rtmon.c
	gcc -o test_set_rtmon -O2 test_set_rtmon.c

clean:
	rm -f test_rtmon 2> /dev/null
	rm -f test_print_rtmon 2> /dev/null
	rm -f test_cancel_rtmon 2> /dev/null
	rm -f test_set_rtmon 2> /dev/null
